// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFvNAu8tGd7Da9kvznRZ_o1QIUGuePVk',
    appId: '1:276792499756:web:ebf8be816d0ffd5615fb89',
    messagingSenderId: '276792499756',
    projectId: 'aplikasicatatankuliah',
    authDomain: 'aplikasicatatankuliah.firebaseapp.com',
    databaseURL: 'https://aplikasicatatankuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah.firebasestorage.app',
    measurementId: 'G-76H6T04LYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJRNjoO6EuMG7wWPWkxMZHWLEvmyuLzc',
    appId: '1:276792499756:android:ee07e3332ec532da15fb89',
    messagingSenderId: '276792499756',
    projectId: 'aplikasicatatankuliah',
    databaseURL: 'https://aplikasicatatankuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAslXvnt7iKnvmPFoWR7TqLIDvBwzJOM0Y',
    appId: '1:276792499756:ios:5e5371951f76fc8715fb89',
    messagingSenderId: '276792499756',
    projectId: 'aplikasicatatankuliah',
    databaseURL: 'https://aplikasicatatankuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah.firebasestorage.app',
    iosBundleId: 'com.example.aplikasicatatankuliah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAslXvnt7iKnvmPFoWR7TqLIDvBwzJOM0Y',
    appId: '1:276792499756:ios:5e5371951f76fc8715fb89',
    messagingSenderId: '276792499756',
    projectId: 'aplikasicatatankuliah',
    databaseURL: 'https://aplikasicatatankuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah.firebasestorage.app',
    iosBundleId: 'com.example.aplikasicatatankuliah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFvNAu8tGd7Da9kvznRZ_o1QIUGuePVk',
    appId: '1:276792499756:web:a3659c9c766bfde815fb89',
    messagingSenderId: '276792499756',
    projectId: 'aplikasicatatankuliah',
    authDomain: 'aplikasicatatankuliah.firebaseapp.com',
    databaseURL: 'https://aplikasicatatankuliah-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasicatatankuliah.firebasestorage.app',
    measurementId: 'G-0T3GX75YJP',
  );
}
